"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
var cors_middleware_1 = require("../middleware/cors-middleware");
var transfer_controller_1 = require("../controller/transfer-controller");
var transferRoutes = express_1.default.Router();
transferRoutes.get('/transfer', (0, cors_1.default)(cors_middleware_1.default.limitedClient), transfer_controller_1.getAllTransferList);
transferRoutes.get('/transfer/:id', (0, cors_1.default)(cors_middleware_1.default.limitedClient), transfer_controller_1.getTransferList);
transferRoutes.post('/transfer', (0, cors_1.default)(cors_middleware_1.default.limitedClient), transfer_controller_1.createTransferData);
transferRoutes.options('/transfer/:id', (0, cors_1.default)(cors_middleware_1.default.globalClient));
transferRoutes.options('/transfer/:id', (0, cors_1.default)(cors_middleware_1.default.limitedClient));
transferRoutes.post('/transfer', (0, cors_1.default)(cors_middleware_1.default.limitedClient));
transferRoutes.patch('/transfer/:id', (0, cors_1.default)(cors_middleware_1.default.globalClient), transfer_controller_1.updateTransferData);
transferRoutes.delete('/transfer/:id', (0, cors_1.default)(cors_middleware_1.default.globalClient), transfer_controller_1.deleteTransferData);
exports.default = transferRoutes;
