"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var dotenv_1 = require("dotenv");
dotenv_1.default.config();
var username = process.env.DB_ATLAS_USER;
var password = process.env.DB_ATLAS_PASS;
var cluster = process.env.DB_ATLAS_CLUSTER;
var dbname = process.env.DB_ATLAS_NAME;
var dbConfig = { username: username, password: password, cluster: cluster, dbname: dbname };
exports.default = dbConfig;
